/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemRouteImport } from './routes/system'
import { Route as StrategiesRouteImport } from './routes/strategies'
import { Route as StocksRouteImport } from './routes/stocks'
import { Route as SelectionHistoryRouteImport } from './routes/selection-history'
import { Route as SelectionRouteImport } from './routes/selection'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as KhunterRouteImport } from './routes/khunter'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as IndexRouteImport } from './routes/index'

const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesRoute = StrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksRoute = StocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectionHistoryRoute = SelectionHistoryRouteImport.update({
  id: '/selection-history',
  path: '/selection-history',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectionRoute = SelectionRouteImport.update({
  id: '/selection',
  path: '/selection',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const KhunterRoute = KhunterRouteImport.update({
  id: '/khunter',
  path: '/khunter',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/backtest': typeof BacktestRoute
  '/khunter': typeof KhunterRoute
  '/risk': typeof RiskRoute
  '/selection': typeof SelectionRoute
  '/selection-history': typeof SelectionHistoryRoute
  '/stocks': typeof StocksRoute
  '/strategies': typeof StrategiesRoute
  '/system': typeof SystemRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/backtest': typeof BacktestRoute
  '/khunter': typeof KhunterRoute
  '/risk': typeof RiskRoute
  '/selection': typeof SelectionRoute
  '/selection-history': typeof SelectionHistoryRoute
  '/stocks': typeof StocksRoute
  '/strategies': typeof StrategiesRoute
  '/system': typeof SystemRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/backtest': typeof BacktestRoute
  '/khunter': typeof KhunterRoute
  '/risk': typeof RiskRoute
  '/selection': typeof SelectionRoute
  '/selection-history': typeof SelectionHistoryRoute
  '/stocks': typeof StocksRoute
  '/strategies': typeof StrategiesRoute
  '/system': typeof SystemRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/backtest'
    | '/khunter'
    | '/risk'
    | '/selection'
    | '/selection-history'
    | '/stocks'
    | '/strategies'
    | '/system'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/backtest'
    | '/khunter'
    | '/risk'
    | '/selection'
    | '/selection-history'
    | '/stocks'
    | '/strategies'
    | '/system'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/backtest'
    | '/khunter'
    | '/risk'
    | '/selection'
    | '/selection-history'
    | '/stocks'
    | '/strategies'
    | '/system'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  BacktestRoute: typeof BacktestRoute
  KhunterRoute: typeof KhunterRoute
  RiskRoute: typeof RiskRoute
  SelectionRoute: typeof SelectionRoute
  SelectionHistoryRoute: typeof SelectionHistoryRoute
  StocksRoute: typeof StocksRoute
  StrategiesRoute: typeof StrategiesRoute
  SystemRoute: typeof SystemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies': {
      id: '/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof StrategiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks': {
      id: '/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof StocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selection-history': {
      id: '/selection-history'
      path: '/selection-history'
      fullPath: '/selection-history'
      preLoaderRoute: typeof SelectionHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selection': {
      id: '/selection'
      path: '/selection'
      fullPath: '/selection'
      preLoaderRoute: typeof SelectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khunter': {
      id: '/khunter'
      path: '/khunter'
      fullPath: '/khunter'
      preLoaderRoute: typeof KhunterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  BacktestRoute: BacktestRoute,
  KhunterRoute: KhunterRoute,
  RiskRoute: RiskRoute,
  SelectionRoute: SelectionRoute,
  SelectionHistoryRoute: SelectionHistoryRoute,
  StocksRoute: StocksRoute,
  StrategiesRoute: StrategiesRoute,
  SystemRoute: SystemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
